"""Boolean fields added

Revision ID: 776f2548a240
Revises: 0868ce2ef62f
Create Date: 2025-06-29 23:17:22.005196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '776f2548a240'
down_revision = '0868ce2ef62f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('publish', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_column('publish')
        batch_op.drop_column('status')
        batch_op.drop_column('favorite')

    # ### end Alembic commands ###
